### ISSUE TITLE
UnicodeEncodeError when describing project with 'åäö'

### ISSUE THREAD

**Issue by mrksbrg** [orion-research/coach#1]
I used Swedish 'åäö' in both the title and description of a new case.

Traceback (most recent call last):
  File "C:\Users\Markus\Anaconda3\lib\site-packages\flask\app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Markus\Anaconda3\lib\site-packages\flask\app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "C:\Users\Markus\Anaconda3\lib\site-packages\flask\app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Markus\Anaconda3\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\Markus\Anaconda3\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Markus\Anaconda3\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Markus\Anaconda3\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Markus\Anaconda3\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\Markus\Anaconda3\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Markus\Anaconda3\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File ".\..\COACH\framework\coach.py", line 230, in wrapping
    
  File "C:\Users\Markus\Anaconda3\lib\encodings\cp437.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 16-17: character maps to <undefined>

**Comment by jakobaxelsson** [comment]
Seems to be a general problem related to unicode characters. Same problem appears if you create an alternative using these characters in the title.

**Comment by jakobaxelsson** [comment]
Adding the attribute accept-charset="UTF-8" to the FORM element in the HTML page seems to solve the issue. Has to be fixed in all templates.

**Comment by jakobaxelsson** [comment]
Resolved by adding information about accept-charset in form elements, and adding meta information to html page headers.
