### ISSUE TITLE
User profile dialogue does not show

### ISSUE THREAD

**Issue by mrksbrg** [orion-research/coach#3]
The user profile dialogue does not show. Traceback:

An error occured while processing the endpoint user_profile_dialogue_transition:
Service: InteractionService running at 127.0.0.1:5000
Arguments: []
Traceback (most recent call last):
  File ".\..\COACH\framework\coach.py", line 233, in wrapping
    result = m(*args)
  File ".\..\COACH\framework\InteractionService.py", line 517, in user_profile_dialogue_transition
    'email': self.authentication_service_proxy.get_user_email(user_id = session["user_id"]),
  File ".\..\COACH\framework\coach.py", line 364, in service_call
    raise MicroserviceException(message + result.text)
COACH.framework.coach.MicroserviceException: An error occured while processing the endpoint get_user_name:
Service: http://127.0.0.1:5009
Arguments: {'user_id': 'markus'}

An error occured while processing the endpoint get_user_name:
Service: AuthenticationService running at 127.0.0.1:5009
Arguments: [('user_id', 'markus')]
Traceback (most recent call last):
  File ".\..\COACH\framework\coach.py", line 233, in wrapping
    result = m(*args)
  File ".\..\COACH\framework\AuthenticationService.py", line 263, in get_user_name
    return self.users[user_id]["name"]
KeyError: 'name'

**Comment by mrksbrg** [comment]
The bug is repeatable and appears when opening the user profile after having changed the user password. Some state must be invalid.
